---
- name: Install QEMU Guest Agent on Debian-based systems
  hosts: all
  become: yes
  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present

    - name: Ensure qemu-guest-agent is started and enabled
      service:
        name: qemu-guest-agent
        state: started
        enabled: yes
