---
- name: Install CIFS Utilities
  hosts: all
  become: yes
  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Install cifs-utils package
      apt:
        name: cifs-utils
        state: present
